Traceback (most recent call last):
  File "C:\Users\seanc\AppData\Roaming\Python\Python38\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\seanc\AppData\Roaming\Python\Python38\site-packages\nbclient\client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\seanc\AppData\Roaming\Python\Python38\site-packages\nbclient\util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\seanc\AppData\Roaming\Python\Python38\site-packages\nbclient\util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\seanc\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\seanc\AppData\Roaming\Python\Python38\site-packages\nbclient\client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "C:\Users\seanc\AppData\Roaming\Python\Python38\site-packages\nbclient\client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\seanc\AppData\Roaming\Python\Python38\site-packages\nbclient\client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
raw = pd.read_excel("../data/FrontiersDS.xlsx", sheet_name="Wide", skiprows=3)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mImportError[0m                               Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_16004/1211535765.py[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [0mraw[0m [1;33m=[0m [0mpd[0m[1;33m.[0m[0mread_excel[0m[1;33m([0m[1;34m"../data/FrontiersDS.xlsx"[0m[1;33m,[0m [0msheet_name[0m[1;33m=[0m[1;34m"Wide"[0m[1;33m,[0m [0mskiprows[0m[1;33m=[0m[1;36m3[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;32m~\AppData\Roaming\Python\Python38\site-packages\pandas\io\excel\_base.py[0m in [0;36mread_excel[1;34m(io, sheet_name, header, names, index_col, usecols, squeeze, dtype, engine, converters, true_values, false_values, skiprows, nrows, na_values, keep_default_na, verbose, parse_dates, date_parser, thousands, comment, skipfooter, convert_float, mangle_dupe_cols, **kwds)[0m
[0;32m    302[0m [1;33m[0m[0m
[0;32m    303[0m     [1;32mif[0m [1;32mnot[0m [0misinstance[0m[1;33m([0m[0mio[0m[1;33m,[0m [0mExcelFile[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 304[1;33m         [0mio[0m [1;33m=[0m [0mExcelFile[0m[1;33m([0m[0mio[0m[1;33m,[0m [0mengine[0m[1;33m=[0m[0mengine[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    305[0m     [1;32melif[0m [0mengine[0m [1;32mand[0m [0mengine[0m [1;33m!=[0m [0mio[0m[1;33m.[0m[0mengine[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    306[0m         raise ValueError(

[1;32m~\AppData\Roaming\Python\Python38\site-packages\pandas\io\excel\_base.py[0m in [0;36m__init__[1;34m(self, io, engine)[0m
[0;32m    822[0m         [0mself[0m[1;33m.[0m[0m_io[0m [1;33m=[0m [0mstringify_path[0m[1;33m([0m[0mio[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m    823[0m [1;33m[0m[0m
[1;32m--> 824[1;33m         [0mself[0m[1;33m.[0m[0m_reader[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0m_engines[0m[1;33m[[0m[0mengine[0m[1;33m][0m[1;33m([0m[0mself[0m[1;33m.[0m[0m_io[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    825[0m [1;33m[0m[0m
[0;32m    826[0m     [1;32mdef[0m [0m__fspath__[0m[1;33m([0m[0mself[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\AppData\Roaming\Python\Python38\site-packages\pandas\io\excel\_xlrd.py[0m in [0;36m__init__[1;34m(self, filepath_or_buffer)[0m
[0;32m     18[0m         """
[0;32m     19[0m         [0merr_msg[0m [1;33m=[0m [1;34m"Install xlrd >= 1.0.0 for Excel support"[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 20[1;33m         [0mimport_optional_dependency[0m[1;33m([0m[1;34m"xlrd"[0m[1;33m,[0m [0mextra[0m[1;33m=[0m[0merr_msg[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     21[0m         [0msuper[0m[1;33m([0m[1;33m)[0m[1;33m.[0m[0m__init__[0m[1;33m([0m[0mfilepath_or_buffer[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m     22[0m [1;33m[0m[0m

[1;32m~\AppData\Roaming\Python\Python38\site-packages\pandas\compat\_optional.py[0m in [0;36mimport_optional_dependency[1;34m(name, extra, raise_on_missing, on_version)[0m
[0;32m     90[0m     [1;32mexcept[0m [0mImportError[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m     91[0m         [1;32mif[0m [0mraise_on_missing[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 92[1;33m             [1;32mraise[0m [0mImportError[0m[1;33m([0m[0mmsg[0m[1;33m)[0m [1;32mfrom[0m [1;32mNone[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     93[0m         [1;32melse[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m     94[0m             [1;32mreturn[0m [1;32mNone[0m[1;33m[0m[1;33m[0m[0m

[1;31mImportError[0m: Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.
ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.

